name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: ../../github-metrics.svg
          template: classic
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Berlin
          base: "metadata"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_recent_days: 0
          plugin_languages_ignored: css, html, ShaderLab, HLSL
          config_order: isocalendar, languages, base.metadata
